---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

inputs:
- name: microservices
- name: version
  optional: true

outputs:
- name: assets

caches:
- path: gopath/

run:
  path: microservices-demo/ci/build.yml
