---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vinod18/testimage
    tag: '1.0'  

inputs:
- name: microservices
- name: version
  optional: true

outputs:
- name: assets

caches:
- path: gopath/

run:
  path: microservices-demo/ci/build.yml
  

#run:
#  path: docker 
#  args:
#  - build -t vinod18/testimage .
#  
